version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Mysql123@
      MYSQL_USER: user
      MYSQL_PASSWORD: Mysql123@
    volumes:
      - 1625d0fa15494c654c78caa17c230ffa78b98ce2676d5ee77877f663add4ed98:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  1625d0fa15494c654c78caa17c230ffa78b98ce2676d5ee77877f663add4ed98:
