server:
  port: 8081

spring:
  datasource:
    url : "jdbc:mysql://103.216.116.98:3306/book_rating_db"
    username : admin
    password : admin123!@#
    # url: "jdbc:mysql://localhost:3306/book_rating_db"
    # username: root
    # password: Mysql123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: buihuuduy1612@gmail.com
    password: oinxblxxlqyheerm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "K7j0LshncymqxUzj5inOflDE4ooSNfWFxps6VzBhVyGB2HytlsWhywvHE6VYxifs
"